travis:
  secure:
    BINSTAR_TOKEN: sCwL0SlkIjLMjHUIF0PgOPegS8XySlqrVb3mwDxAlTJUCkzFVzS5OhoRipzIa3NDWCXRgozu1juHxo87Mat/NhcUFpViEm/q3l0+V3Oxmu+79lOXW+ogSsvMHvN51+tGmjdyZ62KtKV5ddxIh3dlV7goLzZpILvkZPnfeKO6xnsz+zAg/hmCGIhPYcRe7Vx1KEq/QB9g8vRciQAoc8bw0csci2SOnf6c+0USsGQKAu+UcUnv85RruI7t6qKqLrbIYqqSj3WaT84wiNMHXVqIU07CZwQpscokpVtcdazk9Z0bdBg7t0/vACcumM7uweW6tOBpn3vFLfopCUlBwiOUUoBP6nR8bnTNYwpk3ObAbrAQrFDioCu5zX3Q6nK0T1aH6ZkV//gToUNaze73YrRj3lLT/pq0hBqTlsQoMgynxGMlONtAXpyBBoHYjeCqs4AvE8Rzl8Nz1kD8KAw2ymNkQQ1Adw1VqLsbpeZ+0y9WkNC64RK1biM4ogr8txD4IfKJSAGzr39GudIbTGQfTDf+tDCFlfTwnPPKJvCZE/7ykxqmGHvKGZhjbXZjhrrRjHiNQAqrm1IFhca2FW/UBLF8H6qPCQikvHkSwTA7FWzB5L+e/tD4MFJa7GedGDUjpl1nDAExMssu7/MJqbf77nKmSHpAwYm6gpI/GRvCi4qxNEg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
